### ISSUE TITLE
antialiasing?

### ISSUE THREAD

**Issue by GenesisAria** [Arion-Kun/TogglePostProcessing#5]
enables some kind of built-in pp antialiasing, can't remove it without disabling everything.

**Comment by JustArion** [comment]
If the fix is possible to toggle the anti-aliasing would it be preferred to be a Toggle in the MelonPreferences or would you say to just disable it if its found?, I will have to investigate further but hopefully you can contribute some information regarding this bug, did this appear in a world that normally has Post Processing or normally doesn't? also does it occur during the loading screen (between worlds)?

**Comment by GenesisAria** [comment]
yes, it was applying what looks like really poorly configured (default) FXAA or SMAA that makes small text unreadable until i override it to off.  it counts as if it is one of the world ones, as if i check it to not apply to world, it doesn't remove it anymore.  i exclude the md and the pp aa is gone.

**Comment by JustArion** [comment]
Mind testing this build to see if you notice the AA? I've changed the assetbundle's interal settings and changed it to MSAA x8 and Ultra Quality (Highest)

(Github doesn't accept .dll uploads so its in a zip)
Attached Below:
[PostProcessing.zip](https://github.com/Arion-Kun/PostProcessing/files/6372912/PostProcessing.zip)
